version: "3"

services:

  client:
    build: ./client
    volumes:
        - ./client:/patchup/client
        - /patchup/client/node_modules
    ports:
        - "3000:3000"
    stdin_open: true
    container_name: patchup-client
    links:
      - server