version: "3"

services:

  client:
    build: ./client
    volumes:
      - ./client:/patchup/client
      - /patchup/client/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    container_name: patchup-client

  server:
    build: ./server
    volumes:
      - ./server:/patchup/server
      - /patchup/server/node_modules
    environment:
      - MONGO_HOST=patchup-database
      - MONGO_PORT=27107
      - NODE_ENV=development
    ports:
      - 8080:8080
    stdin_open: true
    container_name: patchup-server
    networks:
      - patchup-network

  database:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/database
      - MONGO_LOG_DIR=/dev/null
    volumes: 
      - ./.database:/database
    ports: 
      - 27017:27107
    container_name: patchup-database
    logging:
      driver: none
    networks:
      - patchup-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - 4563-4584:4563-4584
      - 8055:8080
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./.localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  patchup-network:
    driver: bridge
