name: patchup

static_sites:
  - name: patchup-client
    source_dir: client
    build_command: yarn export
    output_dir: build
    environment_slug: node-js
    github:
      repo: Dezyh/patchup
      branch: master
      deploy_on_push: true
      
