name: Patchup CLI

on:
  push:
    paths:
      - cli/**
      - .github/workflows/cli.yml
    branches: 
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: cli
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with: 
          profile: minimal
          toolchain: stable

      - name: Rust Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

  package:
    name: Package
    runs-on: ubuntu-latest
    
    needs:
      - build

    outputs:
      name: ${{ steps.metadata.outputs.name }}
      version: ${{ steps.metadata.outputs.version }}
      description: ${{ steps.metadata.outputs.description }}
      license: ${{ steps.metadata.outputs.license }}
      url: ${{ steps.metadata.outputs.url }}

    steps:
      - uses: actions/checkout@v2

      - name: Extract Metadata
        id: metadata
        run: ./pkg/metadata.sh 

      - name: Create Release Archive
        run: tar -czf patchup-cli.tar.gz Cargo.lock Cargo.toml src

      - name: Create Binary Release Archive
        run: tar -czf patchup-cli-bin.tar.gz target/release/patchup

      - name: Upload Release Archive
        uses: svenstaro/upload-release-action@v2
        with: repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cli/patchup-cli.tar.gz 
          tag: ${{ steps.metadata.outputs.version }}
          overwrite: true

      - name: Upload Binary Release Archive
        uses: svenstaro/upload-release-action@v2
        with: repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cli/patchup-cli-bin.tar.gz 
          tag: ${{ steps.metadata.outputs.version }}
          overwrite: true
        
#      - name: Publish to AUR
#        uses: KSXGitHub/github-actions-deploy-aur@v2.2.3
#        with:
#          pkgname: patchup-bin
#          pkgbuild: ./cli/PKGBUILD
#          commit_username: ${{ secrets.AUR_USERNAME }}
#          commit_email: ${{ secrets.AUR_EMAIL }}
#          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
