name: cli

on:
  push:
    paths:
      - cli/**
      - .github/workflows/cli.yml
    branches: 
      - master

jobs:
  cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with: 
          profile: minimal
          toolchain: stable

      - name: Rust Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Generate PKGBUILD
        run: cargo install cargo-aur && cargo aur
        
      - name: Cheeky LS
        run: ls && find ./ -name PKGBUILD

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.3
        with:
          pkgname: patchup
          pkgbuild: ./cli/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

